### ISSUE TITLE
harpy default params buggy

### ISSUE THREAD

**Issue by awegsche** [pylhc/omc3#68] opened 2019-07-15 11:48 UTC
Crash when calling harpy (run_per_bunch) with default params from `harpy_params()`:

https://github.com/pylhc/omc3/blob/398bed5d675a4ccde17ae3e0fd88752569274627/omc3/hole_in_one.py#L332-L417

with Error Message:
`ERR: TypeError: '>' not supported between instances of 'float' and 'dict'`

on
<pre><font color="#CD3232"><b>ERR: </b></font>  File <font color="#CDCDFF"><b>/media/awegsche/HDD/omc3/omc3/harpy/clean.py</b></font>: line <font color="#00C800"><b>103</b></font>, in <b>_detect_bpms_with_spikes</b>
<font color="#6482FF">FILE </font>    <font color="#64C864"> 98 </font>    return bpm_flatness
<font color="#6482FF">FILE </font>    <font color="#64C864"> 99 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864">100 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864">101 </font>def _detect_bpms_with_spikes(bpm_data, max_peak_cut):
<font color="#6482FF">FILE </font>    <font color="#64C864">102 </font>    &quot;&quot;&quot;  Detects BPMs with spikes &gt; max_peak_cut  &quot;&quot;&quot;
<font color="#6482FF">FILE </font>--&gt; <font color="#00C800"><b>103 </b></font>    too_high = bpm_data[bpm_data.max(axis=1) &gt; max_peak_cut].index
<font color="#6482FF">FILE </font>    <font color="#64C864">104 </font>    too_low = bpm_data[bpm_data.min(axis=1) &lt; -max_peak_cut].index
<font color="#6482FF">FILE </font>    <font color="#64C864">105 </font>    bpm_spikes = too_high.union(too_low)
<font color="#6482FF">FILE </font>    <font color="#64C864">106 </font>    if bpm_spikes.size:
<font color="#6482FF">FILE </font>    <font color="#64C864">107 </font>        LOGGER.debug(f&quot;Spikes &gt; {max_peak_cut} detected. BPMs removed: {bpm_spikes.size}&quot;)
<font color="#6482FF">FILE </font>    <font color="#64C864">108 </font>    return bpm_spikes
</pre>

Full Error Log:

<pre><font color="#CD3232"><b>ERR: </b></font><font color="#FABE50">Traceback (most recent call last):</font>
<font color="#CD3232"><b>ERR: </b></font>  File <font color="#CDCDFF"><b>do_petra_analysis.py</b></font>: line <font color="#00C800"><b>47</b></font>, in <b>&lt;module&gt;</b>
<font color="#6482FF">FILE </font>    <font color="#64C864"> 42 </font>    data = {}
<font color="#6482FF">FILE </font>    <font color="#64C864"> 43 </font>    data[&apos;X&apos;] = pd.read_pickle(os.path.join(m.rawpath, &quot;x_data&quot;))
<font color="#6482FF">FILE </font>    <font color="#64C864"> 44 </font>    data[&apos;Y&apos;] = pd.read_pickle(os.path.join(m.rawpath, &quot;y_data&quot;))
<font color="#6482FF">FILE </font>    <font color="#64C864"> 45 </font>    print(data[&apos;X&apos;])
<font color="#6482FF">FILE </font>    <font color="#64C864"> 46 </font>
<font color="#6482FF">FILE </font>--&gt; <font color="#00C800"><b> 47 </b></font>    lin_files.append(handler.run_per_bunch(TbtData([data], None, [0], 13000), hp))
<font color="#6482FF">FILE </font>    <font color="#64C864"> 48 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864"> 49 </font>op = get_optics_params()
<font color="#6482FF">FILE </font>    <font color="#64C864"> 50 </font>op.outputdir = os.path.join(&quot;output&quot;, SELECTION + &quot;_output_&quot; + ID)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 51 </font>op.modeldir = &quot;./2019_june_26_desy&quot;
<font color="#6482FF">FILE </font>    <font color="#64C864"> 52 </font>op.accelerator = &quot;petra&quot;
<font color="#CD3232"><b>ERR: </b></font><font color="#FABE50">    lin_files.append(handler.run_per_bunch(TbtData([data], None, [0], 13000), hp))</font>
<font color="#CD3232"><b>ERR: </b></font>  File <font color="#CDCDFF"><b>/media/awegsche/HDD/omc3/omc3/harpy/handler.py</b></font>: line <font color="#00C800"><b>43</b></font>, in <b>run_per_bunch</b>
<font color="#6482FF">FILE </font>    <font color="#64C864"> 38 </font>    bpm_datas, usvs, lins, bad_bpms = {}, {}, {}, {}
<font color="#6482FF">FILE </font>    <font color="#64C864"> 39 </font>    output_file_path = _get_output_path_without_suffix(harpy_input.outputdir, harpy_input.files)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 40 </font>    for plane in PLANES:
<font color="#6482FF">FILE </font>    <font color="#64C864"> 41 </font>        bpm_data = _get_cut_tbt_matrix(tbt_data, harpy_input.turns, plane)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 42 </font>        bpm_data = _scale_to_mm(bpm_data, harpy_input.unit)
<font color="#6482FF">FILE </font>--&gt; <font color="#00C800"><b> 43 </b></font>        bpm_data, usvs[plane], bad_bpms[plane], bpm_res = clean.clean(harpy_input, bpm_data, model)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 44 </font>        lins[plane], bpm_datas[plane] = _closed_orbit_analysis(bpm_data, model, bpm_res)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 45 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864"> 46 </font>    tune_estimates = harpy_input.tunes if harpy_input.autotunes is None else frequency.estimate_tunes(
<font color="#6482FF">FILE </font>    <font color="#64C864"> 47 </font>        harpy_input, usvs if harpy_input.clean else
<font color="#6482FF">FILE </font>    <font color="#64C864"> 48 </font>        dict(X=clean.svd_decomposition(bpm_datas[&quot;X&quot;], harpy_input.sing_val),
<font color="#CD3232"><b>ERR: </b></font><font color="#FABE50">    bpm_data, usvs[plane], bad_bpms[plane], bpm_res = clean.clean(harpy_input, bpm_data, model)</font>
<font color="#CD3232"><b>ERR: </b></font>  File <font color="#CDCDFF"><b>/media/awegsche/HDD/omc3/omc3/harpy/clean.py</b></font>: line <font color="#00C800"><b>39</b></font>, in <b>clean</b>
<font color="#6482FF">FILE </font>    <font color="#64C864"> 34 </font>        return bpm_data, None, [], None
<font color="#6482FF">FILE </font>    <font color="#64C864"> 35 </font>    bpm_data, bpms_not_in_model = _get_only_model_bpms(bpm_data, model)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 36 </font>    if bpm_data.empty:
<font color="#6482FF">FILE </font>    <font color="#64C864"> 37 </font>        raise AssertionError(&quot;Check BPMs names! None of the BPMs was found in the model!&quot;)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 38 </font>    with timeit(lambda spanned: LOGGER.debug(f&quot;Time for filtering: {spanned}&quot;)):
<font color="#6482FF">FILE </font>--&gt; <font color="#00C800"><b> 39 </b></font>        bpm_data, bad_bpms_clean = _cut_cleaning(harpy_input, bpm_data, model)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 40 </font>    with timeit(lambda spanned: LOGGER.debug(f&quot;Time for SVD clean: {spanned}&quot;)):
<font color="#6482FF">FILE </font>    <font color="#64C864"> 41 </font>        bpm_data, bpm_res, bad_bpms_svd, usv = _svd_clean(bpm_data, harpy_input)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 42 </font>        all_bad_bpms = bpms_not_in_model + bad_bpms_clean + bad_bpms_svd
<font color="#6482FF">FILE </font>    <font color="#64C864"> 43 </font>    return bpm_data, usv, all_bad_bpms, bpm_res
<font color="#6482FF">FILE </font>    <font color="#64C864"> 44 </font>
<font color="#CD3232"><b>ERR: </b></font><font color="#FABE50">    bpm_data, bad_bpms_clean = _cut_cleaning(harpy_input, bpm_data, model)</font>
<font color="#CD3232"><b>ERR: </b></font>  File <font color="#CDCDFF"><b>/media/awegsche/HDD/omc3/omc3/harpy/clean.py</b></font>: line <font color="#00C800"><b>56</b></font>, in <b>_cut_cleaning</b>
<font color="#6482FF">FILE </font>    <font color="#64C864"> 51 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864"> 52 </font>def _cut_cleaning(harpy_input, bpm_data, model):
<font color="#6482FF">FILE </font>    <font color="#64C864"> 53 </font>    LOGGER.debug(f&quot;Number of BPMs in the input {bpm_data.index.size}&quot;)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 54 </font>    known_bad_bpms = _detect_known_bad_bpms(bpm_data, harpy_input.bad_bpms)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 55 </font>    bpm_flatness = _detect_flat_bpms(bpm_data, harpy_input.peak_to_peak)
<font color="#6482FF">FILE </font>--&gt; <font color="#00C800"><b> 56 </b></font>    bpm_spikes = _detect_bpms_with_spikes(bpm_data, harpy_input.max_peak)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 57 </font>    exact_zeros = _detect_bpms_with_exact_zeros(bpm_data, harpy_input.keep_exact_zeros)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 58 </font>    all_bad_bpms = _index_union(known_bad_bpms, bpm_flatness, bpm_spikes, exact_zeros)
<font color="#6482FF">FILE </font>    <font color="#64C864"> 59 </font>    original_bpms = bpm_data.index
<font color="#6482FF">FILE </font>    <font color="#64C864"> 60 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864"> 61 </font>    bpm_data = bpm_data.loc[bpm_data.index.difference(all_bad_bpms)]
<font color="#CD3232"><b>ERR: </b></font><font color="#FABE50">    bpm_spikes = _detect_bpms_with_spikes(bpm_data, harpy_input.max_peak)</font>
<font color="#CD3232"><b>ERR: </b></font>  File <font color="#CDCDFF"><b>/media/awegsche/HDD/omc3/omc3/harpy/clean.py</b></font>: line <font color="#00C800"><b>103</b></font>, in <b>_detect_bpms_with_spikes</b>
<font color="#6482FF">FILE </font>    <font color="#64C864"> 98 </font>    return bpm_flatness
<font color="#6482FF">FILE </font>    <font color="#64C864"> 99 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864">100 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864">101 </font>def _detect_bpms_with_spikes(bpm_data, max_peak_cut):
<font color="#6482FF">FILE </font>    <font color="#64C864">102 </font>    &quot;&quot;&quot;  Detects BPMs with spikes &gt; max_peak_cut  &quot;&quot;&quot;
<font color="#6482FF">FILE </font>--&gt; <font color="#00C800"><b>103 </b></font>    too_high = bpm_data[bpm_data.max(axis=1) &gt; max_peak_cut].index
<font color="#6482FF">FILE </font>    <font color="#64C864">104 </font>    too_low = bpm_data[bpm_data.min(axis=1) &lt; -max_peak_cut].index
<font color="#6482FF">FILE </font>    <font color="#64C864">105 </font>    bpm_spikes = too_high.union(too_low)
<font color="#6482FF">FILE </font>    <font color="#64C864">106 </font>    if bpm_spikes.size:
<font color="#6482FF">FILE </font>    <font color="#64C864">107 </font>        LOGGER.debug(f&quot;Spikes &gt; {max_peak_cut} detected. BPMs removed: {bpm_spikes.size}&quot;)
<font color="#6482FF">FILE </font>    <font color="#64C864">108 </font>    return bpm_spikes
<font color="#CD3232"><b>ERR: </b></font><font color="#FABE50">    too_high = bpm_data[bpm_data.max(axis=1) &gt; max_peak_cut].index</font>
<font color="#CD3232"><b>ERR: </b></font>  File <font color="#CDCDFF"><b>/home/awegsche/anaconda3/envs/pythonthree/lib/python3.7/site-packages/pandas/core/ops.py</b></font>: line <font color="#00C800"><b>1766</b></font>, in <b>wrapper</b>
<font color="#6482FF">FILE </font>    <font color="#64C864">1761 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864">1762 </font>        else:
<font color="#6482FF">FILE </font>    <font color="#64C864">1763 </font>            values = self.get_values()
<font color="#6482FF">FILE </font>    <font color="#64C864">1764 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864">1765 </font>            with np.errstate(all=&apos;ignore&apos;):
<font color="#6482FF">FILE </font>--&gt; <font color="#00C800"><b>1766 </b></font>                res = na_op(values, other)
<font color="#6482FF">FILE </font>    <font color="#64C864">1767 </font>            if is_scalar(res):
<font color="#6482FF">FILE </font>    <font color="#64C864">1768 </font>                raise TypeError(&apos;Could not compare {typ} type with Series&apos;
<font color="#6482FF">FILE </font>    <font color="#64C864">1769 </font>                                .format(typ=type(other)))
<font color="#6482FF">FILE </font>    <font color="#64C864">1770 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864">1771 </font>            # always return a full value series here
<font color="#CD3232"><b>ERR: </b></font><font color="#FABE50">    res = na_op(values, other)</font>
<font color="#CD3232"><b>ERR: </b></font>  File <font color="#CDCDFF"><b>/home/awegsche/anaconda3/envs/pythonthree/lib/python3.7/site-packages/pandas/core/ops.py</b></font>: line <font color="#00C800"><b>1649</b></font>, in <b>na_op</b>
<font color="#6482FF">FILE </font>    <font color="#64C864">1644 </font>                x = x.view(&apos;i8&apos;)
<font color="#6482FF">FILE </font>    <font color="#64C864">1645 </font>
<font color="#6482FF">FILE </font>    <font color="#64C864">1646 </font>            method = getattr(x, op_name, None)
<font color="#6482FF">FILE </font>    <font color="#64C864">1647 </font>            if method is not None:
<font color="#6482FF">FILE </font>    <font color="#64C864">1648 </font>                with np.errstate(all=&apos;ignore&apos;):
<font color="#6482FF">FILE </font>--&gt; <font color="#00C800"><b>1649 </b></font>                    result = method(y)
<font color="#6482FF">FILE </font>    <font color="#64C864">1650 </font>                if result is NotImplemented:
<font color="#6482FF">FILE </font>    <font color="#64C864">1651 </font>                    return invalid_comparison(x, y, op)
<font color="#6482FF">FILE </font>    <font color="#64C864">1652 </font>            else:
<font color="#6482FF">FILE </font>    <font color="#64C864">1653 </font>                result = op(x, y)
<font color="#6482FF">FILE </font>    <font color="#64C864">1654 </font>
<font color="#CD3232"><b>ERR: </b></font><font color="#FABE50">    result = method(y)</font>
<font color="#CD3232"><b>ERR: </b></font><font color="#32F0FF">TypeError</font>: &apos;&gt;&apos; not supported between instances of &apos;float&apos; and &apos;dict&apos;
</pre>

**Comment by lmalina** [comment] 2019-07-15 12:09
The harpy test is running fine, both in python 3.6 and 3.7, as well as with pandas version 0.23 and 0.24. In this case, I would suspect corrupted input data, since the pandas.read_pickle method is not considered safe. The pickled files themselves depend on Python version and are not compatible between Python 2 and 3.

**Comment by awegsche** [comment] 2019-07-15 12:14
setting a costum value `hp.max_peak=20.0` solves the issue.

Nothing to do with the pickled data _at this point_. I will check the integrity of the dataframes nonetheless for the subsequent analysis steps.

**Comment by lmalina** [comment] 2019-07-15 12:43
As discussed offline, the problem is in use the harpy_options() unparsed. Closing the issue.

**Closed by lmalina** 2019-07-15 12:43 UTC
Labels: bug

**Comment by awegsche** [comment] 2019-07-15 12:54
I will add the correct usage for future reference:

`options, rest = Entrypoint(harpy_params()).parse(args)`

where args is e.g. a dictionary holding the mandatory and needed options.

example:

```
hp_args, _ = EntryPoint(harpy_params()).parse({
    "files":['file1'],
    "outputdir": harpy_outdir,
    "model": './2019_june_26_desy/twiss.dat',
    "turns":[0,10000],
    "clean": True,
    "bad_bpms": ["BPM_SOL_24"],
    "first_bpm": 'BPM_SWR_13',
    "wrong_polarity_bpms": [],
    "autotunes": "transverse"
})
```
